### ISSUE TITLE
List sports places implementation details

### ISSUE THREAD

**Issue by lauri-n** [lipas-liikuntapaikat/lipas-api#3]
Could you provide some details on how the GET /api/sports-places method works.

When listing sports places with the closeTo parameters specified are the results returned in any specific order? Getting them sorted by distance to the requested point would make it easier to find out the closest N places with less additional requests needed. Of course sorting like might have some performance implications in the backend.

Also, how are sports places with LineString geometry types handled when listing with closeTo parameters? Is it based on the start, end, any or all points of the LineString being inside the requested radius to the closeTo point? For my use case I would prefer having these routes/linestrings returned when any of the points are within the radius. Best option could be to have a parameter to control this behavior: start/end/any.

**Comment by vharmain** [comment]
Sure, we use ElasticSearch as a search-backend and `closeTo` uses [Geo-distance query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html) with default settings. ~~I think it matches any point in LineStrings and Polygons.~~ The results are not sorted.

I'm happy to add support for sorting the results. We could add a `sort` query parameter where, for example, `sort=distance` would return the results sorted by the distance. Would that work for your use-case?

What comes to start/end points in routes; this is something that ElasticSearch doesn't support directly (as far as I know). We could index the start/end points as separate fields and then use `geo_distance` to match them as desired. This is a bit larger change and requires a little bit of thinking. It's not a huge change though. I will definitely consider this. Is it a showstopper for you if LineStrings and Polygons are matched by any point? 

We also have a [Geoserver](http://lipas.cc.jyu.fi/geoserver/web/) that is capable to perform pretty much [any imaginable spatial queries](https://docs.geoserver.org/latest/en/user/filter/function_reference.html). It's not as nice to use as the REST-api though.

**EDIT**: Sorry, I re-read your message and noticed that matching by `any` point is exactly what you want.

**EDIT2**: argh, I remembered wrong. We're currently indexing only the start-points of more complex geometries. I'm not happy with this and I'll change it in the next update so that geometries are indexed "as is". I'll probably need to preserve the current behaviour as default and do as you proposed and add an option to match any point. Thanks for bringing this up!

**Comment by lauri-n** [comment]
Yes, I guess for both cases a new query parameter is needed with the current behavior as default so as to not break any existing integrations.

For the route matching parameter I can think of the following options:

- `start`: matches the start point, current behavior and default
- `end`: matches the end point, maybe only relevant if the route is one-directional
- `endpoint`: matches either end of the route
- `any`: matches any point on the route

For my case the `any` option is enough but I can imagine the `endpoint` option being useful for many cases as well. Also might be worth considering/documenting would this affect only LineStrings or Polygons as well.

**Comment by vharmain** [comment]
@lauri-n I've now added  `closeToMatch` query parameter that accepts values `start-point` and `any-point`. I will add support for endpoints if someone requests. Could you please give it a spin and let me know if it works as you expect.

**Comment by lauri-n** [comment]
The new search option seems to be working nicely. However now all get sports place requests are returning 500.

For example: http://lipas.cc.jyu.fi/api/sports-places/526414

```
{
  "errors": {
    "location": {
      "geom-coll": "disallowed-key"
    }
  }
}
```

**Comment by vharmain** [comment]
Woops, regression. Fixed now! Thanks again for reporting.

**Comment by vharmain** [comment]
Closing.
