### ISSUE TITLE
Last page of paginated results missing links and X-total-count headers

### ISSUE THREAD

**Issue by Jepyhaja** [lipas-liikuntapaikat/lipas-api#5]
When querying the api one page at a time the last page does not have the links header containing the links to first, prev, next and last pages.
X-total-count seems to be missing too.

**Comment by vharmain** [comment]
Thanks for reporting @Jepyhaja ! 

This was a logical mistake that had remained unnoticed since 2016. :)

It's now fixed so that `x-total-count` and `link` headers are returned also for complete (HTTP 200) responses. Previously they were present only for partial (HTTP 206) responses. If the response is a "complete response" (HTTP 200), meaning a full response or the last page, there's no `rel=next` in the `link` header because there's nothing more left.

Please let me know if the fix works for you, and I'll close the issue.

**Comment by Jepyhaja** [comment]
Well that was quick! 
Seems to be working as expected now.

Thanks!
